CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    password VARCHAR(999) NOT NULL,
    activate BOOLEAN NOT NULL,
    activation_code VARCHAR(45) NOT NULL,
    can_change_password BOOLEAN NOT NULL,
    swiped INTEGER,
    swiped_categories INTEGER,
    created_cards INTEGER,
    created_categories INTEGER,
    level FLOAT NOT NULL,
    change_password_code VARCHAR(45) NOT NULL
);

CREATE TABLE roles (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45)
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    primary key(user_id, role_id),
    foreign key(user_id) references users (id),
    foreign key(role_id) references roles (id)
);

CREATE TABLE cards (
    id BIGSERIAL PRIMARY KEY,
    engtext VARCHAR(45) NOT NULL,
    rustext VARCHAR(45) NOT NULL,
    is_public BOOLEAN NOT NULL,
    author_id BIGINT NOT NULL,
    image BYTEA
);

CREATE TABLE categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE categories_cards(
    category_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    primary key(category_id, card_id),
    foreign key(category_id) references categories(id),
    foreign key(card_id) references cards(id)
);

CREATE TABLE trains (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL
);

CREATE TABLE trains_cards(
    train_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    primary key(train_id, card_id),
    foreign key(train_id) references trains(id),
    foreign key(card_id) references cards(id)
);

INSERT INTO users (username, email, password, activate, activation_code, can_change_password, change_password_code, level, swiped, swiped_categories, created_cards, created_categories)
VALUES
('admin', 'admin@gmail.com', '$2a$04$.ixf22M0GMkzYwj5ewmsP.VbNaNaXxgn.0u1Yx4pYsMUH5VOnSb3O', TRUE, '100000', FALSE, '100000', 1.0, 45, 3, 3, 2),
('user', 'user@gmail.com', '$2a$04$.ixf22M0GMkzYwj5ewmsP.VbNaNaXxgn.0u1Yx4pYsMUH5VOnSb3O', TRUE, '100000', FALSE, '100000', 1.0, 45, 3, 3, 2);

INSERT INTO roles (name)
VALUES
('ROLE_ADMIN'),
('ROLE_USER');

INSERT INTO users_roles (user_id, role_id)
VALUES
(1, 1),
(2, 2);

INSERT INTO cards (engtext, rustext, author_id, is_public)
VALUES
('Apple', 'Яблоко', 1, FALSE),
('Banana', 'Банан', 1, FALSE),
('Orange', 'Апельсин', 1, FALSE),
('Grape', 'Виноград', 1, FALSE),
('Pear', 'Груша', 1, FALSE),
('Strawberry', 'Клубника', 1, FALSE),
('Blueberry', 'Черника', 1, FALSE),
('Raspberry', 'Малина', 1, FALSE),
('Mango', 'Манго', 1, FALSE),
('Pineapple', 'Ананас', 1, FALSE),
('Watermelon', 'Арбуз', 1, FALSE),
('Kiwi', 'Киви', 1, FALSE),
('Lemon', 'Лимон', 1, FALSE),
('Lime', 'Лайм', 1, FALSE),
('Grapefruit', 'Грейпфрут', 1, FALSE),
('Pomegranate', 'Гранат', 1, FALSE),
('Avocado', 'Авокадо', 1, FALSE),
('Coconut', 'Кокос', 1, FALSE),
('Cherry', 'Вишня', 1, FALSE),
('Peach', 'Персик', 1, FALSE),

('Dog', 'Собака', 1, FALSE),
('Cat', 'Кошка', 1, FALSE),
('Rabbit', 'Кролик', 1, FALSE),
('Hamster', 'Хомяк', 1, FALSE),
('Guinea Pig', 'Морская свинка', 1, FALSE),
('Ferret', 'Хорек', 1, FALSE),
('Turtle', 'Черепаха', 1, FALSE),
('Parrot', 'Попугай', 1, FALSE),
('Goldfish', 'Золотая рыбка', 1, FALSE),
('Lizard', 'Ящерица', 1, FALSE),
('Snake', 'Змея', 1, FALSE),
('Bird', 'Птица', 1, FALSE),
('Elephant', 'Слон', 1, FALSE),
('Giraffe', 'Жираф', 1, FALSE),
('Lion', 'Лев', 1, FALSE),
('Tiger', 'Тигр', 1, FALSE),
('Zebra', 'Зебра', 1, FALSE),
('Panda', 'Панда', 1, FALSE),
('Penguin', 'Пингвин', 1, FALSE),
('Whale', 'Кит', 1, FALSE),

('Sun', 'Солнце', 1, FALSE),
('Moon', 'Луна', 1, FALSE),
('Star', 'Звезда', 1, FALSE),
('Cloud', 'Облако', 1, FALSE),
('Sky', 'Небо', 1, FALSE),
('Rain', 'Дождь', 1, FALSE),
('Snow', 'Снег', 1, FALSE),
('Wind', 'Ветер', 1, FALSE),
('Thunder', 'Гром', 1, FALSE),
('Lightning', 'Молния', 1, FALSE),
('Rainbow', 'Радуга', 1, FALSE),
('Fog', 'Туман', 1, FALSE),
('Sunrise', 'Восход солнца', 1, FALSE),
('Sunset', 'Закат солнца', 1, FALSE),
('Earthquake', 'Землетрясение', 1, FALSE),
('Volcano', 'Вулкан', 1, FALSE),
('Flood', 'Наводнение', 1, FALSE),
('Drought', 'Засуха', 1, FALSE),
('Blizzard', 'Метель', 1, FALSE),
('Tornado', 'Торнадо', 1, FALSE),

('Table', 'Стол', 1, FALSE),
('Chair', 'Стул', 1, FALSE),
('Bed', 'Кровать', 1, FALSE),
('Sofa', 'Диван', 1, FALSE),
('Desk', 'Письменный стол', 1, FALSE),
('Lamp', 'Лампа', 1, FALSE),
('Bookshelf', 'Книжная полка', 1, FALSE),
('Dresser', 'Комод', 1, FALSE),
('Rug', 'Ковер', 1, FALSE),
('Curtain', 'Занавеска', 1, FALSE),
('Pillow', 'Подушка', 1, FALSE),
('Blanket', 'Одеяло', 1, FALSE),
('Mirror', 'Зеркало', 1, FALSE),
('Picture', 'Картина', 1, FALSE),
('Vase', 'Ваза', 1, FALSE),
('Candle', 'Свеча', 1, FALSE),
('Clock', 'Часы', 1, FALSE),
('Shelf', 'Полка', 1, FALSE),
('Nightstand', 'Прикроватная тумбочка', 1, FALSE),
('Cabinet', 'Шкаф', 1, FALSE),

('Car', 'Машина', 1, FALSE),
('Truck', 'Грузовик', 1, FALSE),
('Bicycle', 'Велосипед', 1, FALSE),
('Motorcycle', 'Мотоцикл', 1, FALSE),
('Bus', 'Автобус', 1, FALSE),
('Train', 'Поезд', 1, FALSE),
('Airplane', 'Самолет', 1, FALSE),
('Ship', 'Корабль', 1, FALSE),
('Boat', 'Лодка', 1, FALSE),
('Subway', 'Метро', 1, FALSE),
('Taxi', 'Такси', 1, FALSE),
('Helicopter', 'Вертолет', 1, FALSE),
('Scooter', 'Скутер', 1, FALSE),
('Roller Skates', 'Роликовые коньки', 1, FALSE),
('Skateboard', 'Скейтборд', 1, FALSE),
('Tram', 'Трамвай', 1, FALSE),
('Yacht', 'Яхта', 1, FALSE),
('Steamboat', 'Пароход', 1, FALSE),
('Jet Ski', 'Гидроцикл', 1, FALSE),
('Hovercraft', 'Судно на воздушной подушке', 1, FALSE),

('apple', 'яблоко', 1, TRUE),
('book', 'книга', 1, TRUE),
('chair', 'стул', 1, TRUE),
('dog', 'собака', 1, TRUE),
('table', 'стол', 1, TRUE),
('sun', 'солнце', 1, TRUE),
('water', 'вода', 1, TRUE),
('flower', 'цветок', 1, TRUE),
('house', 'дом', 1, TRUE),
('car', 'автомобиль', 1, TRUE),
('tree', 'дерево', 1, TRUE),
('sky', 'небо', 1, TRUE),
('pencil', 'карандаш', 1, TRUE),
('fish', 'рыба', 1, TRUE),
('bird', 'птица', 1, TRUE),
('window', 'окно', 1, TRUE),
('computer', 'компьютер', 1, TRUE),
('mountain', 'гора', 1, TRUE),
('river', 'река', 1, TRUE),
('flower', 'цветок', 1, TRUE),

('Watcha doin’?', 'Чем сейчас занят?', 1, TRUE),
('Wagwan?', 'Чё там у тебя по жизни?', 1, TRUE),
('Nagwan', 'Так себе', 1, TRUE),
('Hi, howdy?', 'Ну чё, ты как?', 1, TRUE),
('Hiya', 'Э, здоров!', 1, TRUE),
('How you doin’?', 'Как дела?', 1, TRUE),
('Long time no see!', 'Давненько не виделись!', 1, TRUE),
('How are things?', 'Как делишки?', 1, TRUE),
('Take care!', 'Береги себя!', 1, TRUE),
('Till next time!', 'До следующего раза!', 1, TRUE),
('Actually', 'Вообще-то', 1, TRUE),
('Just for the record', 'Чтобы вы знали', 1, TRUE),
('As I said before', 'Как я уже сказал', 1, TRUE),
('If I’m not mistaken', 'Если я не ошибаюсь', 1, TRUE),
('All the same', 'Всё равно', 1, TRUE),
('Either way', 'Так или иначе', 1, TRUE),
('In my opinion', 'Я считаю, что', 1, TRUE),
('Perhaps', 'Возможно', 1, TRUE),
('Probably', 'Вероятно', 1, TRUE),
('Highly likely', 'Весьма вероятно', 1, TRUE),
('It can hardly be so', 'Вряд ли это так', 1, TRUE),
('Most likely', 'Скорее всего', 1, TRUE),
('Most unlikely', 'Вряд ли', 1, TRUE),
('Not a bit', 'Нисколько', 1, TRUE),
('I doubt it', 'У меня есть сомнения', 1, TRUE),
('I’m afraid so', 'Боюсь, это так', 1, TRUE),
('I think I’ll pass', 'Лучше без меня', 1, TRUE),
('I’m not quite sure', 'Я не совсем уверен', 1, TRUE),
('Not a very good idea', 'Не лучшая идея', 1, TRUE),
('Nevermind', 'Неважно', 1, TRUE),
('Did I get it right?', 'Я правильно понял?', 1, TRUE),
('It doesn’t matter', 'Не имеет значения', 1, TRUE),
('Exactly', 'Так точно', 1, TRUE),
('I’m in', 'Я в деле', 1, TRUE),
('Deal!', 'По рукам!', 1, TRUE),
('Hi where!', 'Здорово!', 1, TRUE),
('What’s up?', 'Как ты?', 1, TRUE),
('How’s life?', 'Как жизнь?', 1, TRUE);

CREATE TABLE users_cards (
    user_id BIGINT NOT NULL,
    card_id BIGINT NOT NULL,
    primary key(user_id, card_id),
    foreign key(user_id) references users (id),
    foreign key(card_id) references cards (id)
);

INSERT INTO users_cards (user_id, card_id)
VALUES
(1, 1),
(2, 2);

INSERT INTO categories (name, user_id)
VALUES
('Cat1', 1),
('Cat2', 1);

INSERT INTO categories_cards (category_id, card_id)
VALUES
(1, 1),
(1, 2),
(2, 2),
(2, 3);

INSERT INTO trains (name) VALUES ('Фрукты'), ('Животные'), ('Погода'), ('Мебель'), ('Транспорт'), ('Разное');

INSERT INTO trains_cards (train_id, card_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(1, 10),
(1, 11),
(1, 12),
(1, 13),
(1, 14),
(1, 15),
(1, 16),
(1, 17),
(1, 18),
(1, 19),
(1, 20),
(2, 21),
(2, 22),
(2, 23),
(2, 24),
(2, 25),
(2, 26),
(2, 27),
(2, 28),
(2, 29),
(2, 30),
(2, 31),
(2, 32),
(2, 33),
(2, 34),
(2, 35),
(2, 36),
(2, 37),
(2, 38),
(2, 39),
(2, 40),
(3, 41),
(3, 42),
(3, 43),
(3, 44),
(3, 45),
(3, 46),
(3, 47),
(3, 48),
(3, 49),
(3, 50),
(3, 51),
(3, 52),
(3, 53),
(3, 54),
(3, 55),
(3, 56),
(3, 57),
(3, 58),
(3, 59),
(3, 60),
(4, 61),
(4, 62),
(4, 63),
(4, 64),
(4, 65),
(4, 66),
(4, 67),
(4, 68),
(4, 69),
(4, 70),
(4, 71),
(4, 72),
(4, 73),
(4, 74),
(4, 75),
(4, 76),
(4, 77),
(4, 78),
(4, 79),
(4, 80),
(5, 81),
(5, 82),
(5, 83),
(5, 84),
(5, 85),
(5, 86),
(5, 87),
(5, 88),
(5, 89),
(5, 90),
(5, 91),
(5, 92),
(5, 93),
(5, 94),
(5, 95),
(5, 96),
(5, 97),
(5, 98),
(5, 99),
(5, 100),
(6, 101),
(6, 102),
(6, 103),
(6, 104),
(6, 105),
(6, 106),
(6, 107),
(6, 108),
(6, 109),
(6, 110),
(6, 111),
(6, 112),
(6, 113),
(6, 114),
(6, 115),
(6, 116),
(6, 117),
(6, 118),
(6, 119),
(6, 120);